apiVersion: v2
name: aggregation-layer-example
description: Krateo PlatformOps Aggregation API Layer Example
type: application
icon: "https://github.com/projectkerberus/kerberus-dashboard/blob/main/docs/media/square_black_logo.png"

version: CHART_VERSION
appVersion: APP_VERSION