apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  labels:
    k8s-app: {{ .Chart.Name }}
  name: v1alpha1.example.krateo.dev
spec:
  group: example.krateo.dev
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  service:
    name: {{ .Chart.Name }}
    namespace: kube-system
  version: v1alpha1
  versionPriority: 100