apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: kube-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    k8s-app: {{ .Chart.Name }}
